GeekChicShop/GeekChic

- .gitignore
- src/components/myPage/_Layout.tsx
- src/components/usedHome/UsedItemCard.tsx
- src/components/usedHome/UsedItemList.tsx
- src/pages/MyList.tsx
- src/pages/MyPage.tsx
- src/pages/UsedDetail.tsx
- src/pages/UsedHome.tsx
- src/types/dummyData.ts
- src/types/usedType.ts
- usedItem dummydata생성 후 중고 상품메인 / 상세페이지 연결함
> 더미데이터 생성 후 중고 메인, 상세페이지 완성

- src/pages/Home.tsx
> fix : 검색 params값 버그 수정

- src/components/myPage/Cart.tsx
- src/components/myPage/MyUsedItemList.tsx
- src/components/myPage/OrderList.tsx
- src/pages/MyPage.tsx
- src/pages/MyProfile.tsx
- src/pages/MySalelist.tsx
- src/pages/UsedDetail.tsx
- src/types/dummyData.ts
- src/types/usedType.ts
- 유저 업데이트에 따른 mypage UI및 데이터 업데이트 
- 중고 상세페이지의 뒤로가기 버튼의 상세 기능 추가 
( 중고 메인으로 이동하기가 아닌, 사용자가 사용했던 페이지로 이동할 수 있도록 함 )
> Merge 유저 데이터 업로드 및 Mypage UI + Data 업데이트 

- src/api/firebase.tsx
- src/components/usedHome/UsedItemCard.tsx
- src/components/usedHome/UsedItemList.tsx
- src/pages/UsedDetail.tsx
- src/pages/UsedPostUpload.tsx
- src/types/dummyData.ts
- src/types/usedType.ts
- yarn.lock
- firebase 통신하는 부분과 UI 구성하는 부분 분리
> Feat/upload firebase와 데이터 연결하여 중고 업로드, 중고 메인, 중고 상세 기능 구현 및 UI 생성

- src/api/uploader.tsx
- src/components/common/BottomNav.tsx
- src/components/common/SearchHeader.tsx
- src/pages/UsedPostUpload.tsx
- fileReader()를 사용해 영구적 url을 생성하여 이미지 업로드 했던 부분 업데이트함
- cloudinary를 사용해 클라우드 서비스로 이미지 업로드 후 해당 이미지 url을 받아서 db에 저장하는 것으로 업데이트 함
> Update : 이미지 업로드 컴포넌트 업데이트 및 사용하지 않는 코드 제거

- src/components/usedHome/SearchList.tsx
- src/components/usedHome/UsedItemList.tsx
- src/pages/UsedHome.tsx
- 중고 메인페이지에서 url의 이동 없이 컴포넌트로 상태 업데이트
- isSearching 상태로 검색결과 컴포넌트 / 중고아이템 컴포넌트로 각각 렌더링 하도록 함
> Merge : feat/search -> dev 로 머지 Update : 검색기능 업데이트

- src/components/usedHome/SearchList.tsx
- src/components/usedHome/UsedItemList.tsx
- src/components/usedHome/UsedSearchBar.tsx
- src/pages/UsedHome.tsx
- usedHome에서 중고 데이터를 관리하기는 것으로 변경 ( 이전에는 usedItemList에서 데이터 받아옴 )
- 중고 메인에서 전체 데이터 /검색 데이터를 받아 해당 컴포넌트로 넘겨줌
- 검색어와 각 데이터는 useState로 상태를 관리하고 있음
- 검색바 컴포넌트에서는 검색어 상태를 관리
> Update : 중고 메인 검색기능 업데이트 , 검색바 컴포넌트 생성

- src/pages/UsedHome.tsx
- 전체 중고 아이템 데이터 불러오는 것과 검색 데이터 불러오는 것을 reqct-query로 관리하도록 함
> merge : dev -> main , Update : react-query로 usedHome 데이터 상태관리함

- src/api/firebase.tsx
- src/pages/MyPage.tsx
- src/pages/UsedPostUpload.tsx
- src/types/usedType.ts
- 로그인 한 유저의 기본 데이터 email, avatar, username, uid를 바탕으로 
서비스에서 필요한 데이터를 추가하여 firebase DB의 userData에 생성 
- '' 빈 데이터는 프로필 수정에서 채울 수 있도록 기능 구현해야 함
> Merge : Feat/mypage -> dev : 로그인 한 유저 데이터 firebase db로 업로드 , dev full 받고 작업해주세요

- src/components/myPage/Cart.tsx
- src/components/myPage/MyUsedItemList.tsx
- src/components/myPage/OrderList.tsx
- src/pages/MyList.tsx
- src/pages/MyPage.tsx
- src/pages/MyProfile.tsx
- src/pages/MySalelist.tsx
- src/types/dummyData.ts
- src/types/usedType.ts
- 유저의 주문내역, 판매목록, 장바구니 데이터를 각 페이지에 연결함
- react-router-dom의 Link컴포넌트의 state를 사용해 데이터를 넘겨 사용
- useLocation()메서드를 사용함
> Update : 유저 데이터 연결한 뒤 mypage 각 페이지 데이터 연결

- src/main.tsx
- src/pages/UsedDetail.tsx
- src/pages/UsedMessage.tsx
- 해당 아이템의 정보를 가지고 Message페이지로 이동
- Link컴포넌트의 state를 통해 필요한 데이터를 보내고 받음
> Merge : feat/talk -> dev : 중고 상세페이지에서 쪽지 보내기 기능 구현 시작

- src/api/firebase.tsx
- src/components/myPage/Cart.tsx
- src/components/myPage/MyUsedItemList.tsx
- src/components/myPage/OrderList.tsx
- src/components/usedHome/SearchList.tsx
- src/components/usedHome/UsedItemCard.tsx
- src/components/usedHome/UsedItemList.tsx
- src/pages/MyPage.tsx
- src/pages/MySalelist.tsx
- src/pages/UsedDetail.tsx
- src/pages/UsedHome.tsx
- src/types/usedType.ts
- 중복되는 타입 제거 및 수정 
- 마이페이지의 각 탭에서 사용되는 데이터 타입 확인 -> 메인, 중고 데이터 타입 체크
- Product와 UsedItem이 공통으로 사용되는 컴포넌트 ( 주문내역 ) 타입 업데이트
- 타입 수정에 따라 연결된 페이지 타입 수정
> Merge : Feat/mypage -> dev : 타입 수정 -> 마이페이지 탭에서 사용하는 데이터 타입에 따라 렌더링을 함

- src/components/myPage/MyUsedItemList.tsx
- src/components/myPage/OrderList.tsx
- src/pages/MyPage.tsx
- src/types/utils.ts
- 더미데이터를 배열로 생성후 컴포넌트 렌더링 해 놓은 것에서 실제 데이터(객체) 연결하니 에러남  
- 컴포넌트 렌더링 코드 객체 -> 배열로 변환함
> Merge : deat/my -> dev : 주문내역 데이터 연결 후 컴포넌트 렌더링 에러 체크 

- src/components/common/BottomNav.tsx
- src/components/myPage/Cart.tsx
- src/components/myPage/MyUsedItemList.tsx
- src/components/myPage/OrderList.tsx
- src/components/myPage/_Layout.tsx
- src/pages/Home.tsx
- src/pages/MyList.tsx
- src/pages/MyPage.tsx
- src/pages/MyProfile.tsx
- src/pages/MySalelist.tsx
- src/pages/UsedHome.tsx
- src/pages/UsedPostUpload.tsx
- src/types/usedType.ts
- src/types/utils.ts
- 데이터 없는 경우 null, undefined의 경우 업데이트함. 
- .......................................힝 
- ㅋㅋㅋㅋㅋ으아!!!!!!!!!
> Merge : Feat/my -> dev : dev pull받고 작업해주세요~

- src/pages/UsedDetail.tsx
- src/pages/UsedMessage.tsx
- src/pages/UsedMessageList.tsx
- 중고 상세페이지에서 쪽지 보내기 -> 쪽지방 이동 하는 것과
- 마이페이지에서 -> 쪽지리스트 보기 -> 쪽지방 이동할 때 데이터 받는 부분 통일
- 쪽지 데이터 렌더링 UI 완성
- 남은 것 : firebase에 데이터 추가 & state 업데이트하기
> Merge : feat/message -> dev : 쪽지방 구현

- src/api/firebase.tsx
- src/components/main/Comment.tsx
- src/pages/NewProduct.tsx
- src/pages/OrdersDetail.tsx
- 잘못된 타입 추론에 의해 useQueryKey 에러가 뜨는것으로 짐작됨
> Fix : OrdersDetail 기능 에러 수정중

- src/api/firebase.tsx
- src/components/myPage/MyUsedItemList.tsx
- src/components/myPage/OrderList.tsx
- src/pages/MyList.tsx
- src/pages/MyPage.tsx
- src/pages/OrdersDetail.tsx
- OrderList페이지 에러에 의해 개별적으로 useQuery 사용해서 데이터를 가져왔는데. 생각해보니 모든 데이터가 아니라 해당 주문내역 id 관련된 order데이터를 가져와야 함으로 props로 보내기로 함
- 그 과정속에서 OrderList 페이지 오류나는 코드 일부 비활성화
> Update : 주문내역 기능 수정 및 구현

- src/components/myPage/OrderList.tsx
- src/types/utils.ts
UI 렌더링 에러 해결했는데 확인해보실래여 되는지!
아래 부분에서 orders를 map돌리는게 아니라 orders.items를 map돌려야했던 거였서요.
> Update : 주문 상세보기 UI렌더링 에러 해결

- src/assets/icons/king.svg
- src/components/common/IsSeller.tsx
- src/components/myPage/Cart.tsx
- src/components/myPage/OrderList.tsx
- src/components/myPage/_Layout.tsx
- src/components/usedHome/UsedItemCard.tsx
- src/pages/MyPage.tsx
- src/pages/MySalelist.tsx
- src/pages/UsedDetail.tsx
- src/pages/UsedHome.tsx
- src/pages/UsedMessage.tsx
- src/pages/UsedMessageList.tsx
- src/types/utils.ts
- 쪽지 페이지에서 뒤로가기 버튼 클릭 -> 마이 -> 쪽지 리스트로 이동되도록 함
- 로그인 한 유저가 판매자인 경우 icon표시 및 버튼 안보이게 ( 쪽지 리스트, 중고 메인 )
- 로그인 한 유저가 판매자인지 확인하는 컴포넌트 생성
> Merge : Feat/message-> dev : 쪽지보내기 기능 업데이트 

- src/components/myPage/CartItem.tsx
- src/components/myPage/MyCart.tsx
- src/components/payment/PaymentCard.tsx
- src/components/usedDetail/UsedComment.tsx
- src/components/usedDetail/UsedInputComment.tsx
- src/pages/MyPage.tsx
- src/pages/MySalelist.tsx
- src/pages/Payment.tsx
- src/pages/ProductsDtail.tsx
- src/pages/UsedDetail.tsx
- 변경 전 : useState를 사용해 comment 데이터를 업데이트
- 변경 후 : react-query의 mutation을 사용해 데이터 업데이트
> Merge : Feat/detail -> dev : comment 상태관리 업데이트 

- src/pages/OrdersDetail.tsx
- src/pages/Payment.tsx
- 주문 하기 완료시 주문내역으로 이동하고 싶은데 orders데이터를 읽을 수 없는 에러 뜸 -> 확인해서 에러 수정
> Update : 주문내역, 주문하기 완료 시 페이지 이동

- src/components/main/Comment.tsx
- src/components/main/CommentCard.tsx
> Upadate : 댓글 평점 기능, 레이아웃  구현

- src/api/firebase.tsx
- src/pages/Home.tsx
- src/pages/NewProduct.tsx
- 상품등록 useMutation을 사용하여 구현함 
- 이후 댓글 부분도 useMutation 사용하여 구현할 예정
> Update : 상품 등록 useMutation 사용하여 구현

- src/api/firebase.tsx
- src/components/myPage/Notification.tsx
- src/pages/MySalelist.tsx
- src/pages/UsedDetail.tsx
- src/pages/UsedMessage.tsx
- src/pages/UsedMessageList.tsx
- src/types/usedType.ts
- 쪽지 보내기 페이지에서 중고 제품 결제하는 것으로 변경
- 그에 따른 세부 구현 업데이트
> Merge : Feat/mypage -> dev : 결제하기 기능 업데이트 
